### PR TITLE
WebApp: Implemented publish-subscriber model on y-utils to better manage collaborative session events

### PR DESCRIPTION
**Pull request by aksh-konda**
## What has been done
* To better manage the session events implemented publish-subscriber model
* Currently the Collaborative session has 2 events: HostJoined and HostLeft
* There are 2 main use cases of these events
1. When Peer joins first and Host has not arrived yet, the Peer should listen to the HostJoined event and then HostLeft event.

https://user-images.githubusercontent.com/63443657/122102425-08218300-ce33-11eb-9b51-ec4c54fa1921.mp4

2. When the Host leaves and Peer is still Online, the Peer should listen to the HostLeft event and the HostJoined event.

https://user-images.githubusercontent.com/63443657/122101733-4c605380-ce32-11eb-8b68-74c06f4a2f5d.mp4

### CODE REVIEW

**Comment by aksh-konda** [comment]
Changed the logo to:



I Hope it's looking good.

**Comment by laurent22** [comment]
Looks good, I didn't notice any particular issue. Did you run a linter on the code?

**Comment by aksh-konda** [comment]
Yes, I think create-react-app by default has eslinter enabled and has some strict rules. do you want me to add any specific linting configurations?

**Comment by aksh-konda** [comment]
yes... I think I need to add rules for the indentations, quotes, and things like that. will do! thanks for pointing it out.

**Comment by laurent22** [comment]
It's up to you for the linter. Just one thing - if you process all the code base with the linter, please create a separate pull request for this, otherwise it will be difficult to find the relevant changes in all the changed files.

**Review by laurent22 — APPROVED** [review]

**Review by roman-r-m — APPROVED** [review]

**Pull request merged**
