### PR TITLE
WebApp: Added fetch toolbar option

### PR DESCRIPTION
**Pull request by aksh-konda**
# What has been done
* Added fetch option
* Added thunk action to load note from Joplin
* Some minor Changes to the toolbar

# Demos
* ### Minor Changes
ToolbarChanges1

* ### Working of fetch option
ToolbarChanges2

### CODE REVIEW

**Comment by roman-r-m** [comment]
Do I understand correctly that it will overwrite any changes made in the web app? Maybe there should be a warning somewhere?

**Comment by aksh-konda** [comment]
> Do I understand correctly that it will overwrite any changes made in the web app? Maybe there should be a warning somewhere?

I thought about this problem too. But if the user wants previous contents back it's as simple as `ctrl+z` but then the resources will be lost. Sure this is a problem, I'll work on it.

**Comment by laurent22** [comment]
@Aksh-Konda, when adding a new feature, I think it would be good to add the documentation too, as part of the same commit.

Also I don't quite understand how it can work. If any user makes any chance in the web app, it should update the note in Joplin, is that correct? But with this new button, it implies you should be able to edit the note in Joplin, without your changes being overwritten by the web app. Could you clarify a bit how it works?

**Comment by aksh-konda** [comment]
> @Aksh-Konda, when adding a new feature, I think it would be good to add the documentation too, as part of the same commit.

Sure!


> Also I don't quite understand how it can work. If any user makes any chance in the web app, it should update the note in Joplin, is that correct?

I currently made it the Host's choice to save the content when he feels the changes are as desired (so not all the gibberish gets saved to Joplin).

**Comment by laurent22** [comment]
> I currently made it the Host's choice to save the content when he feels the changes are as desired (so not all the gibberish gets saved to Joplin).

Ok I thought it was automatically saved, so it makes sense then.

**Review by laurent22 — APPROVED** [review]

**Comment by laurent22** [comment]
Very good documentation, thanks for adding this!

**Pull request merged**
