### PR TITLE
Implemented Initial plugin

### PR DESCRIPTION
**Pull request by aksh-konda**
## What has been done
* Added settings to collect web app URL

* Added an option to the toolbar to open the web app passing noteId and token as route params

* Made Changes accordingly to the web app.

## Demo

https://user-images.githubusercontent.com/63443657/124359355-33cda700-dc42-11eb-855e-892ab5a1e8e4.mp4

### CODE REVIEW

**Comment by PackElend** [comment]
could  we see synced changes as well in the video?

**Comment by aksh-konda** [comment]
> could  we see synced changes as well in the video?

I didn't exactly understand what synced changes mean..🤔

**Comment by PackElend** [comment]
> synced changes mean.

a change in the left window should be shown on the right window

**Comment by aksh-konda** [comment]
Like changes in Joplin should sync with the web app and vice versa?

Or is it the changes being reflected in other instances of the web app?

**Comment by Aksh-Konda** [comment]
@PackElend ?

**Comment by PackElend** [comment]
I meant the collaboration in action. Are we able to see it, somehow?

**Comment by aksh-konda** [comment]
Yes it's the same as previous, nothing is changed and changes to the note in the web app gets synced as demonstrated in previous PRs for the web app.

I have to add save and invite as initial toolbar options. Which will demonstrate the working project...

**Comment by PackElend** [comment]
forgot the other videos, the answer is in #2 :) 
may collect the videos in a list in readme.md?

**Comment by aksh-konda** [comment]
I was planning on doing the README.md, Once a working project has been developed. Hopefully by Monday or Tuesday.

**Pull request merged**
